### ISSUE TITLE
Can we add cookies in headers while connecting with WebSockets?

### ISSUE THREAD

**Issue by ketangoyani** [dcoded/flume.ws#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dcoded** [comment]
I'll take a look into this to see what it would take to make this work. How would you suggest these cookies be passed into the agent? Would a new configuration property work for you to pass multiple cookie names and values?

**Comment by ketangoyani** [comment]
I have written for cookies. which can take multiple cookies together.

**Comment by dcoded** [comment]
@ketangoyani ,

I've added the capability to pass multiple cookies via the config file and have updated the README to give an example how to do so. Let me know if this works for you!
