### ISSUE TITLE
Retrieve data continuously

### ISSUE THREAD

**Issue by kikoB** [dcoded/flume.ws#2]
Is it possible to configure the source to retrieve data continuously? 

When I start the flume agent I receive the init message, but then nothing. Is there any parameter to setup in order to continuously retrieve some data? Or it has to be implemented?

Thank you for your answer.

**Comment by dcoded** [comment]
Hi kikoB,

The client should be forwarding data as fast as the websocket server is pushing it to the client. I'll take a look to make sure nothing happened since I've last modified the code.

Is there a public websocket server API you're trying to hit that I can debug against?

**Comment by kikoB** [comment]
Hi dcoded,

as I realized the problem was on our websocket where the data were not forwarding continuously. We have the websocket on private network and it should be fixed next days.

Hopefully it will work, but with your implementation should be everything alright, thanks for it.
